module Fsm.Constants.Types where

data InputConstants = InputConstants { inputTimeout :: Int }

data StageConstants = EggConstants { fatalMinTemp :: Int,
                                     medTemp :: Int,
                                     fatalMaxTemp :: Int,
                                     fatalTempSecs :: Int,
                                     duration :: Int,
                                     baseLength :: Double,
                                     baseWeight :: Double } |
                      ChickenConstants { happyIndex :: Int,
                                         depressIndex :: Int,
                                         decreaseMoodSecs :: Int,
                                         depressSecs :: Int,
                                         pooLimit :: Int,
                                         pooLimitSecs :: Int,
                                         fatigueLimit :: Int,
                                         fatigueSecs :: Int,
                                         maxAwakeSecs :: Int,
                                         raiseFatigueSecs :: Int,
                                         lengthFromFull :: Double,
                                         weightFromFull :: Double,
                                         weightLoss :: Double,
                                         pooFromFull :: Int,
                                         pooFromSoSo :: Int,
                                         digestSecs :: Int,
                                         lengthFromPlay :: Double,
                                         sleepingSecs :: Int,
                                         duration :: Int } |
                      AdultConstants { happyIndex :: Int,
                                       depressIndex :: Int,
                                       decreaseMoodSecs :: Int,
                                       depressSecs :: Int,
                                       pooLimit :: Int,
                                       pooLimitSecs :: Int,
                                       fatigueLimit :: Int,
                                       fatigueSecs :: Int,
                                       maxAwakeSecs :: Int,
                                       raiseFatigueSecs :: Int,
                                       lengthFromFull :: Double,
                                       weightFromFull :: Double,
                                       weightLoss :: Double,
                                       pooFromFull :: Int,
                                       pooFromSoSo :: Int,
                                       digestSecs :: Int,
                                       lengthFromPlay :: Double,
                                       sleepingSecs :: Int,
                                       duration :: Int,
                                       medAllowsForElder :: Int } |
                      ElderConstants { happyIndex :: Int,
                                       depressIndex :: Int,
                                       decreaseMoodSecs :: Int,
                                       depressSecs :: Int,
                                       pooLimit :: Int,
                                       pooLimitSecs :: Int,
                                       fatigueLimit :: Int,
                                       fatigueSecs :: Int,
                                       maxAwakeSecs :: Int,
                                       raiseFatigueSecs :: Int,
                                       lengthFromFull :: Double,
                                       weightFromFull :: Double,
                                       weightLoss :: Double,
                                       pooFromFull :: Int,
                                       pooFromSoSo :: Int,
                                       digestSecs :: Int,
                                       lengthFromPlay :: Double,
                                       sleepingSecs :: Int,
                                       weakerInSecs :: Int} deriving Show

data AllConstants = AllConstants {
                          inputConsts :: InputConstants,
                          eggConsts :: StageConstants,
                          chickenConsts :: StageConstants,
                          adultConsts :: StageConstants,
                          elderConsts :: StageConstants
                        }
